# AUTOGENERATED! DO NOT EDIT! File to edit: app.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'image', 'label', 'examples', 'intf', 'classify_image']

# %% app.ipynb 1
from fastai.vision.all import *
import gradio as gr
import timm

# %% app.ipynb 3
learn = load_learner('model.pkl')

# %% app.ipynb 5
categories = ('Academic_Art', 'Art_Nouveau', 'Baroque', 'Expressionism', 'Japanese_Art', 'Neoclassicism', 'Primitivism', 
              'Realism', 'Renaissance', 'Rococo', 'Romanticism', 'Symbolism', 'Western_Medieval')

def classify_image(img):
    pred, idx, probs = learn.predict(img)
    return dict(zip(categories, map(float, probs)))

# %% app.ipynb 7
image = gr.Image(height=224, width=224)
label = gr.Label()
examples = ['images/renaissance_art.jpg', 'images/baroque_art.jpg', 
            'images/romanticism_art.jpg', 'images/realism_art.jpg']
intf = gr.Interface(fn=classify_image, inputs=image, outputs=label, examples=examples)
intf.launch(inline=False)
